server:
  port: ${PORT:${SERVER_PORT:8761}}
spring:
  application:
    name: registry-server
    profiles:
      active: development
eureka:
  instance:
    hostname: registry-server
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://localhost:${server.port}/eureka/