server:
  port: ${PORT:${SERVER_PORT:8890}}
spring:
  application:
    name: product-service
    profiles:
      active: development
  datasource:
    url: jdbc:mysql://localhost:3306/Ecommerce?createDatabaseIfNotExist=true
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
        jdbc:
          lob:
            non_contextual_creation: true
    show-sql: true
    generate-ddl: true
    hibernate:
      ddl-auto: update

eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/